apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-app
  template:
    metadata:
      labels:
        app: nestjs-app
    spec:
      containers:
      - name: nestjs-app
        image: my-nestjs-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: booking-app-service
spec:
  selector:
    app: booking-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: NodePort
