apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-app-deployment
  labels:
    app: booking-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-app
  template:
    metadata:
      labels:
        app: booking-app
    spec:
      containers:
      - name: nestjs-app
        image: samiwin/booking-app:1.4
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "1"  # 1 CPU core
            memory: "1Gi"  # 1 GiB
          requests:
            cpu: "1"  # 200 millicores
            memory: "512Mi"  # 512 MiB
