version: '3.9'

services:
  nodeprod:
    build:
        context: .
        dockerfile: Dockerfile
        target: node_production
    volumes:
        - .:/usr/src/app
    ports:
        - "5000:3000"
    extra_hosts:
        - "host.docker.internal:host-gateway"
    command: npm run start:prod


    

  
