version: '3.9'

services:
  nodedev:
    build:
        context: .
        dockerfile: Dockerfile
        target: node_development
    volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
    ports:
        - "3500:3000"
    extra_hosts:
        - "host.docker.internal:host-gateway"
    command: npm run start:dev


    

  
