apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: <base64-encoded-ca-cert>  # Placeholder for the actual CA certificate
    server: https://<your-k8s-api-server>:6443           # Placeholder for the actual Kubernetes API server URL
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: samib
  name: jenkins-context
current-context: jenkins-context
users:
- name: samib
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ijd1TVF3UmhJaGJIRGJCaXlYT0dscWxmc202YnVSUGMtdDBZUXFJdVZwaFkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImplbmtpbnMtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiamVua2lucyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImVjMzE1YTE2LTQzNGQtNDkzZS05OGZiLWEzYzE2ZjBlYTU3NCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmplbmtpbnMifQ.G0fTQmPAOKcsoMtbJxjZsKihEFyeGeiTout1jqL_iKupTRp4UUIMOrUHdfhVfU6iqrqiu4n0gfY9fL8nqTig0TSdv0RJkXm9d_44P8kOKnYBDhRmQhrCVrrHtG8xhysM_vsmeJG_CqSJVidLkGJY3mqEDk0BIa3DZWoIUzXARUIlhcW5bFyZy5qJXoyuQ5JQYgyjUdEj6Bq7AuKJYSLEtscQWLRUNyYcRKPgRQvXfV2G7Dm3ZfCzQW47zXGkfDsmPApb5ke83b53-Xq3ZGqVe0RqQlH5C_FWwrm9yrxOoSWs1AlP6cw8kJ1UHU-VFrykRrgb7qfk9WMA3HGafuJxGQ
