apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: cGxhY2Vob2xkZXItY2EtY2VydA==  # Placeholder for the actual CA certificate
    server: https://127.0.0.1:58030         # Replace placeholder with the actual Kubernetes API server URL
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: samib
  name: jenkins-context
current-context: jenkins-context
users:
- name: samib
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ijd1TVF3UmhJaGJIRGJCaXlYT0dscWxmc202YnVSUGMtdDBZUXFJdVZwaFkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImplbmtpbnMtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2Nvd
