---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: booking-app-deployment
  namespace: default
  labels:
    app: booking-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-app
  template:
    metadata:
      labels:
        app: booking-app
    spec:
      containers:
      - name: booking-app
        image: "samiwin/booking-app:1.2"
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: booking-app-service
  namespace: default
spec:
  selector:
    app: booking-app
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 3000
    port: 80
